### DAY1 : PART B -- LAST 4 Questions::::///////

-- 5.	Display total amount ordered by each customer from high to low. (donot use sum)


/* A sales and marketing department of this company wants to find out how frequently 
customer have business with them. This can be done in two ways. (Answer Q 6 and Q 7 for the same) */
-- 6 Approach 1. List the current and previous order amount for each customers.


/* 7. Approach 2. Display the customerid, order ids and the 
order dates along with the previous order date and the next order date for every customer in the table:: */


-- 8.	Find out top 3 suppliers in terms of revenue generated by their products.



-- ///////////////////////////////////////////////////////////////////// --

### PART C::: 


-- 1.	Fetch the records to display the customer details who ordered more than 10 products in the single order


-- 2.	Display all the product details with the ordered quantity size as 1.


-- 3.	Display the compan(y)ies which supplies products whose cost is above 100.



-- 4.	Create a combined list to display customers and supplier list as per the below format.


-- 5.	Display the customer list who belongs to same city and country arrange in country wise.



### PART D:::

-- 1.	Company sells the product at different discounted rates. Refer actual product price in product table and selling price in the order item table.
--  Write a query to find out total amount saved in each order then display the orders from highest to lowest amount saved. 





-- 2.	Mr. Kavin want to become a supplier. He got the database of "Richard's Supply" for reference. Help him to pick: 
-- a. List few products that he should choose based on demand.
-- b. Who will be the competitors for him for the products suggested in above questions.




-- 3.	Create a combined list to display customers and suppliers details considering the following criteria 
-- •	Both customer and supplier belong to the same country
-- •	Customer who does not have supplier in their country
-- •	Supplier who does not have customer in their country



-- 4.	Every supplier supplies specific products to the customers. 
-- Create a view of suppliers and total sales made by their products and write a query on this view to find out top 2 suppliers 
-- (using windows function RANK() in each country by total sales done by the products.



